# -*- coding: utf-8 -*-
"""direcciones-PABLO DIAZ

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z3mmRpkLl7otfzaK2_HLx066lR_xo10_
"""

# ===============================
# PARSEADOR DE DIRECCIONES (PERÚ) - v2.6.18 + PATCHES (FULL)
#
# FIXES base:
# 1) Evitar DOMICILIO truncado a mitad -> truncado por componentes + bloqueo de segmentos cortos
# 2) No comerse la "N" final en apellidos tipo "CARRIÓN"
# 3) Fallback agresivo (SN/ACUM.PARC.../PARC...) cuando NO hay vías
# 4) Mantener: series exterior, cochera=estacionamiento, referencia con token válido, etc.
#
# PATCHES adicionales:
# A) Si NO hay vías: DOMICILIO 1 debe iniciar con "SN/" cuando tenga contenido útil (p.ej. COND.xxx)
# B) Si UBICACION (tipo+nombre) ya está representada en DOMICILIO 1, NO repetirla (se limpia UBICACION)
# C) FIX: current_domicilio_len correcto
# D) Si hay >=2 vías detectadas y solo quedó 1 en DOMICILIO, forzar añadir la 2da vía SI cabe completa
# E) FIX: find_all_vias no debe comerse números finales del nombre de vía
# F) Dedupe por contención: evita "PASEO DE LA REPUBLICA ... / DE LA REPUBLICA ..."
# G) LT: prioridad a REFERENCIA; si REFERENCIA no alcanza, LTs sobrantes pueden ir a DOMICILIO; nunca duplicar LT entre ambos
# H) MZ: si N. EXTERIOR usa MZ, no repetir esa MZ en REFERENCIA ni en DOMICILIO (evita triple repetición)
# ===============================

import re
import os
import pandas as pd
import unicodedata

# -------------------------------
# LÍMITES DE COLUMNAS
# -------------------------------
DOMICILIO_MAX = 50
EXT_MAX = 8
INT_MAX = 8
REF_MAX = 25
UBIC_MAX = 30

# -------------------------------
# CONFIG
# -------------------------------
DOMICILIO_WITH_PREFIX = False
TIPO_BONUS = {'AVENIDA': 2, 'JIRON': 1, 'CALLE': 0}

ALLOW_NUMBERS_VIA_2_3 = True
MIN_SECOND_SEG_LEN = 8  # evita extras cortos ("/CAMI", "/SUR")

# -------------------------------
# UTILIDADES
# -------------------------------
def strip_accents(s):
    if not isinstance(s, str):
        return ""
    return ''.join(c for c in unicodedata.normalize('NFD', s)
                   if unicodedata.category(c) != 'Mn')

def norm_spaces(s):
    s = s if isinstance(s, str) else ""
    return re.sub(r'\s+', ' ', s).strip()

def upper(s): return (s or "").upper()
def limit(s, n): return (s or "")[:n]

def default_sn(s):
    s = (s or "").strip()
    return s if s else "SN"

def uniq_preserve(seq):
    out, seen = [], set()
    for x in seq:
        if x not in seen:
            out.append(x); seen.add(x)
    return out

def only_numbers_like(s):
    return bool(s) and re.fullmatch(r'[0-9\.\-\s]+', s.strip()) is not None

def only_digits(s):
    return re.sub(r'[^0-9]', '', s or '')

def has_two_words(s):
    return len([w for w in s.split() if w]) >= 2

def truncate_by_components(s, max_len, sep="/"):
    """
    Trunca sin cortar componentes. Ej: "A/B/C" si no cabe C, queda "A/B".
    """
    s = s or ""
    s = norm_spaces(s).strip(sep)
    if len(s) <= max_len:
        return s
    parts = [p for p in s.split(sep) if p]
    out = ""
    for p in parts:
        cand = (out + (sep if out else "") + p)
        if len(cand) <= max_len:
            out = cand
        else:
            break
    return out

def _canon_text(s: str) -> str:
    s = upper(strip_accents(norm_spaces(s or "")))
    s = re.sub(r'[^A-Z0-9 ]', ' ', s)
    s = norm_spaces(s)
    return s

def _norm_ref_token(tok: str) -> str:
    tok = upper((tok or "").strip())
    tok = re.sub(r'\s+', '', tok)
    tok = tok.strip('-')
    return tok

def is_ref_token_valid(tok: str, allow_letter_only: bool = False) -> bool:
    """
    Acepta: 5, 4C, C4, C-4, B18, B-18, E-07, 12-A, A-12, etc.
    - allow_letter_only=True permite tokens solo letras (ej: "O" en MZ O)
    - si False, exige al menos un dígito (evita basura tipo "DE")
    """
    tok = _norm_ref_token(tok)
    if not tok:
        return False
    if not re.fullmatch(r'[A-Z0-9]+(?:-[A-Z0-9]+)?', tok):
        return False
    if allow_letter_only:
        return True
    return bool(re.search(r'\d', tok))

def base_via_segment(seg: str) -> str:
    """
    Base para dedupe:
    "BOLOGNESI" y "BOLOGNESI 472" => "BOLOGNESI"
    """
    s = upper(norm_spaces(seg or ""))
    s = re.sub(r'\s+\d{1,6}(?:[-‐–—−]\d{1,6}){0,10}\s*$', '', s).strip()
    return s

# ✅ PATCH F: dedupe por contención (evita "PASEO DE ... / DE ...")
def _canon_words(s: str) -> str:
    return _canon_text(s)

def _base_words(seg: str) -> str:
    return _canon_words(base_via_segment(seg))

def is_contained_base(a: str, b: str) -> bool:
    ba = _base_words(a)
    bb = _base_words(b)
    if not ba or not bb:
        return False
    if len(ba.split()) < 2 or len(bb.split()) < 2:
        return False
    return (ba in bb) or (bb in ba)

# Serie abreviada
def abbreviate_series_for_name(nums):
    if not nums: return ""
    parts = [nums[0]]
    for n in nums[1:]:
        parts.append(("." + n[-2:]) if len(n) >= 2 else ("." + n))
    return "".join(parts)

def abbreviate_series_first_last(nums):
    return f"{nums[0]}-{nums[-1]}"

def abbreviate_series_first_last2(nums):
    last = nums[-1]
    tail = last[-2:] if len(last) >= 2 else last
    return f"{nums[0]}-.{tail}"

def abbreviate_series_compact(nums, max_len_allowed):
    """
    Compacta sin cortar “a mitad”. Si no hay espacio suficiente, retorna SOLO el primer valor.
    """
    if not nums:
        return ""
    nums = uniq_preserve(nums)
    if len(nums) <= 1:
        return nums[0]

    if max_len_allowed is None or max_len_allowed <= 0:
        return nums[0]
    if max_len_allowed < len(nums[0]) + 2:
        return nums[0]

    s1 = abbreviate_series_for_name(nums)
    if len(s1) <= max_len_allowed and len(nums) <= 10:
        return s1

    s2 = abbreviate_series_first_last(nums)
    if len(s2) <= max_len_allowed:
        return s2

    s3 = abbreviate_series_first_last2(nums)
    if len(s3) <= max_len_allowed:
        return s3

    return nums[0]

def extract_numbers_series(segment):
    raw = segment
    raw_norm = re.sub(r'[‐-–—−‒﹘﹣－]', '-', raw)
    raw_norm = re.sub(r'\s*-\s*', '-', raw_norm)  # tolera "654- 656"
    nums = re.findall(r'\d{1,6}', raw_norm)
    return nums, raw

# -------------------------------
# VÍAS + DELIMITADORES
# -------------------------------
VIA_PATTERNS = [
    (r'\bavenida\b|\bav(?:enida)?\.?(?=\s|$|[A-Za-zÁÉÍÓÚÜÑáéíóúüñ])|\bavda\.?\b', 'AVENIDA'),
    (r'\bcalle\b|\bcal\.?(?=\s|$|[A-Za-zÁÉÍÓÚÜÑáéíóúüñ])', 'CALLE'),
    (r'\bjir[oó]n\b|\bjr\.?(?=\s|$|[A-Za-zÁÉÍÓÚÜÑáéíóúüñ])', 'JIRON'),
    (r'\bpasaje\b|\bpsj(?:e)?\.?(?=\s|$)|\bpje\.?(?=\s|$)', 'PASAJE'),
    (r'\bprolongaci[oó]n\b|\bprol\.?(?=\s|$)', 'PROLONGACION'),
    (r'\bmalec[oó]n\b|\bml\.?(?=\s|$)', 'MALECON'),
    (r'\bboulevard\b|\bbvd\.?(?=\s|$)|\bbv\.?(?=\s|$)', 'BOULEVARD'),
    (r'\bcarretera\b|\bctra\.?(?=\s|$)|\bcr\.?(?=\s|$)', 'CARRETERA'),
    (r'\bcamino\b', 'CAMINO'),
    (r'\bparque\b|\bpq\.?(?=\s|$)', 'PARQUE'),
    (r'\balameda\b|\bal\.?(?=\s|$)', 'ALAMEDA'),
    (r'\bplaza\b|\bplz\.?(?=\s|$)', 'PLAZA'),
    (r'\b[óo]valo\b|\bovalo\b|\bov\.?(?=\s|$)', 'OVALO'),
    (r'\bautopista\b', 'AUTOPISTA'),
    (r'\bcallej[oó]n\b|\bcjon\.?(?=\s|$)|\bcallej\.?(?=\s|$)', 'CALLEJON'),
    (r'\btransversal\b|\btransv\.?(?=\s|$)|\btv\.?(?=\s|$)', 'TRANSVERSAL'),
    (r'\bv[ií]a\s+expresa\b', 'AVENIDA'),
    (r'\bpaseo\b|\bpas\.?(?=\s|$)', 'PASEO'),
    (r'\bpuente\b|\bpu\.?(?=\s|$)', 'PUENTE'),
    (r'\bcentro\s+comercial\b|\bcc\.?(?=\s|$)', 'CENTRO COMERCIAL'),
    (r'\bgaler[ií]a\b|\bga\.?(?=\s|$)', 'GALERIA'),
]

CONNECTORS = r'\b(con|y|esquina(?:\s+con)?|esq\.?|frente\s+a|que\s+da\s+a|cerca\s+a|a\s+la\s+altura\s+de|altura\s+de|al\s+costado\s+de)\b'
CONNECTORS_RE = re.compile(CONNECTORS, re.I)

NUMTOK = r'(?:n°|nº|nro\.?|nros?\.?|no\.?|num\.?|n[uú]mero)'

DELIMITERS = (
    r'(,|;| - |/|#|' + NUMTOK + r'|\bn\.?(?=\s*\d)|\bkm\b|\bpiso\b|\btorre\b|\bedificio\b|'
    r'\bdepto\b|\bdepartamento\b|\bint\b|\binterior\b|\best(?:\.|acionamiento)?\b|'
    r'\bs[oó]tano\b|\bmanzana\b|\bmz\b|\blote\b|\blt\b|\betapa\b|\bunidad\b|\bunidad inmobiliaria\b|'
    r'\burb\.?\b|\burbanizaci[oó]n\b|\bcondominio\b|\bresidencial\b|\bproyecto\b|'
    + CONNECTORS + r'|$)'
)

ATTR_CUTOFF = r'\b(piso|torre|departamento|dep|dpto|depto|est(?:\.|acionamiento)?|s[oó]tano|manzana|mz|lote|lt|etapa|unidad(?: inmobiliaria)?|edificio|urbanizaci[oó]n|condominio|residencial|proyecto)\b'
ATTR_CUTOFF_RE = re.compile(ATTR_CUTOFF, re.I)

# ✅ PATCH E: find_all_vias separa números finales del nombre (sin cambiar la lógica general)
def find_all_vias(text):
    base = norm_spaces(text)
    low = strip_accents(base.lower())
    vias = []
    for pat, tipo in VIA_PATTERNS:
        for m in re.finditer(pat, low):
            after = base[m.end():]
            nom = re.match(
                r'^\s*([A-Za-zÁÉÍÓÚÜÑáéíóúüñ0-9\-\.\' ]{1,}?)(?=' + DELIMITERS + ')',
                after, re.I
            )

            if nom:
                raw_name = norm_spaces(nom.group(1))

                # Si el nombre termina en número(s) o rango(s), sepáralo:
                # "CAMINOS DEL INCA 508" -> nombre="CAMINOS DEL INCA"
                mnum = re.search(
                    r'\s+\d{1,6}(?:\s*[-–—]\s*\d{1,6}){0,20}\s*$',
                    raw_name
                )
                if mnum:
                    nombre = norm_spaces(raw_name[:mnum.start()])
                    name_end_abs = m.end() + nom.start(1) + mnum.start()
                else:
                    nombre = raw_name
                    name_end_abs = m.end() + nom.end()
            else:
                nombre = ""
                name_end_abs = m.end()

            vias.append({"tipo": tipo, "nombre": nombre, "pos": m.end(), "name_end": name_end_abs})

    return sorted(vias, key=lambda x: x["pos"])

def choose_primary_vias(vias, text, top=3):
    def has_num_after(v):
        seg = text[v["pos"]: v["pos"] + 120]
        for m in re.finditer(NUMTOK + r'\s*\d|km\s*\d|\b\d{1,6}\b', seg, re.I):
            abs_idx = v["pos"] + m.start()
            if "name_end" not in v or abs_idx >= v["name_end"]:
                return True
        return False

    return sorted(
        vias,
        key=lambda v: (
            not has_num_after(v),
            v["pos"],
            -TIPO_BONUS.get(v["tipo"], 0)
        )
    )[:top]

def clean_via_name(name):
    original = name
    name = re.sub(r'\bnum\.?\b', '', name, flags=re.I)
    name = re.sub(r'\bn[uú]mero\b', '', name, flags=re.I)
    name = re.sub(r'\b(que da a|frente a|esquina(?:\s+con)?|esq\.?)\b', '', name, flags=re.I)

    NUMTOK_SUFFIX = r'(?:' + NUMTOK + r'|n\.?(?=\s*\d))'
    name = re.sub(NUMTOK_SUFFIX + r'.*$', '', name, flags=re.I).strip()

    if re.search(r'[A-Za-zÁÉÍÓÚÜÑáéíóúüñ]', name):
        name = re.sub(r'\s*\d{1,6}\s*(?:[-‐-–—−‒﹘﹣－]\s*\d{1,6})?\s*$', '', name).strip()
        name = re.sub(r'[-‐-–—−‒﹘﹣－]\s*$', '', name).strip()

    name = re.sub(r'^[\.\-_/]+\s*', '', name).strip()
    name = re.sub(r'\s+', ' ', name).strip()
    name = re.sub(r'\.+$', '', name).strip()

    if not name or len(name) <= 1:
        name = re.sub(NUMTOK_SUFFIX + r'.*$', '', original, flags=re.I).strip()
        name = re.sub(r'\s*\d{1,6}\s*(?:[-‐-–—−‒﹘﹣－]\s*\d{1,6})?\s*$', '', name).strip()
        name = re.sub(r'[-‐-–—−‒﹘﹣－]\s*$', '', name).strip()
        name = re.sub(r'^[\.\-_/]+\s*', '', name).strip()
        name = re.sub(r'\s+', ' ', name).strip()
        name = re.sub(r'\.+$', '', name).strip()
        if not name:
            name = original

    # ✅ FIX: si el original termina en "...ON" y el limpio quedó en "...O", recupera la N final
    o = upper(strip_accents(norm_spaces(original)))
    n = upper(strip_accents(norm_spaces(name)))
    if o.endswith("ON") and n.endswith("O") and not n.endswith("ON"):
        name = (name + "N").strip()

    return upper(name)

# -------------------------------
# NÚMERO EXTERIOR
# -------------------------------
NEGATIVE_CONTEXT_WORDS = [
    'torre','piso','departamento','dep','dpto','depto',
    'est','estacionamiento','cochera','sotano','sótano',
    'manzana','mz','lote','lt','etapa','unidad','unidad inmobiliaria','edificio',
    'cuadra','cdra',
    'parcela','acumulacion','acumulación',
]

def _has_negative_context(text, start_idx, window=25):
    prev_seg = text[max(0, start_idx-window):start_idx]
    return re.search(r'\b(' + '|'.join(NEGATIVE_CONTEXT_WORDS) + r')\b', prev_seg, re.I) is not None

def extract_exterior(text, primary_vias):
    seg_start = primary_vias[0]["pos"] if primary_vias else 0
    seg = text[seg_start:]

    for m in re.finditer(
        r'(?:\b' + NUMTOK + r'\s*)?(\d{1,6}(?:\s*[-–—]\s*\d{1,6}){1,20})\b',
        seg, re.I
    ):
        if _has_negative_context(seg, m.start(), window=35):
            continue
        nums, raw = extract_numbers_series(m.group(1))
        if nums:
            first = nums[0]
            return limit(upper(first), EXT_MAX), upper(raw)

    for m2 in re.finditer(r'(?:\b' + NUMTOK + r'\s*)?(\d{1,6}(?:[A-Z]|-[0-9A-Z]+)?)\b', seg, re.I):
        if _has_negative_context(seg, m2.start(), window=35):
            continue
        val = upper(m2.group(1))
        return limit(val, EXT_MAX), val

    m3 = re.search(r'\bkm\.?\s*(\d{1,3}(?:[.,]\d{1,2}|\s*1/2)?)\b', seg, re.I)
    if m3:
        raw_km = m3.group(1)
        val_num = raw_km.replace(',', '.')
        val_num = re.sub(r'\s*1/2$', '.5', val_num)
        val = upper(f"KM {val_num}")
        return limit(val, EXT_MAX), val

    if re.search(r'\bs[/ ]?n\b|sin\s+n[uú]mero', seg, re.I):
        return "S/N", "S/N"

    # MZ como exterior (tu lógica)
    mz = re.search(r'\b(mz|manzana)\b\.?\s*([A-Z0-9\-]+)', text, re.I)
    if mz:
        tok = _norm_ref_token(mz.group(2))
        if is_ref_token_valid(tok, allow_letter_only=True):
            val = f"MZ {tok}"
            return limit(val, EXT_MAX), val

    return "", ""

# -------------------------------
# ESQUINA → números para la 2ª vía
# -------------------------------
def extract_corner_numbers_for_second_via(text, via2_pos, lookback=120):
    start = max(0, via2_pos - lookback)
    span = text[start:via2_pos]
    m = re.search(r'(?:esquina|esq\.?)\s+([0-9\-\–\—\s/;,]+?)\s+con\s*$', span, re.I)
    if m:
        nums, _ = extract_numbers_series(m.group(1))
        return nums
    return []

# -------------------------------
# NÚMEROS CERCA DE LA VÍA (filtrados)
# -------------------------------
def numbers_near_via(text, v, is_second=False):
    window = 220
    seg = text[v["pos"]: v["pos"] + window]

    seg = CONNECTORS_RE.split(seg)[0]
    seg = ATTR_CUTOFF_RE.split(seg)[0]

    seg = re.split(r'(?:,|;|/)', seg)[0]
    seg = re.split(r'(?<!\d)\s*-\s*(?!\d)', seg)[0]

    filtered = []
    base_abs = v["pos"]

    for m in re.finditer(r'\d{1,6}', seg):
        abs_idx = base_abs + m.start()
        if "name_end" in v and abs_idx < v["name_end"]:
            continue
        if not _has_negative_context(seg, m.start(), window=20):
            filtered.append(m.group(0))

    if is_second and not filtered:
        filtered = extract_corner_numbers_for_second_via(text, v["pos"])

    return uniq_preserve(filtered), seg

# -------------------------------
# PROYECTO / CONDOMINIO
# -------------------------------
def abbreviate_project_name(name):
    words = [w for w in re.split(r'\s+', upper(name)) if w]
    if len(words) >= 2 and words[0] in ("DE","DEL") and words[1] not in ("LA","EL","LOS","LAS"):
        words = words[1:]
    if not words:
        return upper(name)
    if len(words) == 1:
        return (words[0][:4] + '.') if len(words[0]) > 4 else words[0]
    first = (words[0][:4] + '.') if len(words[0]) > 4 else words[0]
    second = words[1]
    return f"{first}{second}"

def extract_project_condominio_for_domicilio(text):
    t = text
    m = re.search(r'pertenece\s+a\s+([A-Za-zÁÉÍÓÚÜÑáéíóúüñ\' ]+?)\s+condominio\s+([A-Za-zÁÉÍÓÚÜÑáéíóúüñ\' ]+)', t, re.I)
    if m:
        proyecto = norm_spaces(m.group(1))
        cond = norm_spaces(m.group(2))
        proj_abbr = abbreviate_project_name(proyecto)
        return f"{proj_abbr} COND.{upper(cond)}"
    m2 = re.search(r'\bcondominio\b\s+([A-Za-zÁÉÍÓÚÜÑáéíóúüñ\' ]+)', t, re.I)
    if m2:
        cond = norm_spaces(m2.group(1))
        return f"COND.{upper(cond)}"
    return ""

# -------------------------------
# DOMICILIO + HASTA 3 VÍAS
# -------------------------------
ABREV_TIPO = {
    "JIRON": "JR.", "AVENIDA": "AV.", "CALLE": "CAL.", "PASAJE": "PSJE.",
    "PROLONGACION": "PROL.", "MALECON": "MLC.", "BOULEVARD": "BVD.",
    "CARRETERA": "CTRA.", "CAMINO": "CAM.", "PARQUE": "PQ.",
    "ALAMEDA": "AL.", "PLAZA": "PLZ.", "OVALO": "OV.", "AUTOPISTA": "AUT.",
    "CALLEJON": "CLJ.", "TRANSVERSAL": "TRANSV.",
    "PASEO": "PAS.", "PUENTE": "PU.", "CENTRO COMERCIAL": "CC.", "GALERIA": "GA.",
}

def build_via_segment(v, text, index_in_chosen, current_domicilio_len, ext_digits=None):
    name_raw = v["nombre"]
    name = clean_via_name(name_raw)

    if not name:
        after = text[v["pos"]:]
        m_fallback = re.match(r'^\s*([^,;#/\-]{1,}?)(?=' + DELIMITERS + ')', after, flags=re.I)
        if m_fallback:
            name = upper(norm_spaces(m_fallback.group(1)))
        name = clean_via_name(name)

    if v["tipo"] == "PROLONGACION":
        if re.match(r'^(avenida|av\.?)\b', name, re.I):
            name = re.sub(r'^(avenida|av\.?)\b', 'AV.', name, flags=re.I)
        name = f"PROL.{name}"

    nums, _ = numbers_near_via(text, v, is_second=(index_in_chosen == 1))

    if index_in_chosen == 0:
        nums = list(nums)
        if ext_digits:
            nums = [n for n in nums if n != ext_digits]
    else:
        nums = list(nums) if ALLOW_NUMBERS_VIA_2_3 else []

    if re.search(r'\d{2,}', name):
        name = re.sub(r'\d{2,}.*$', '', name).strip()

    seg_core = name

    # 1ª vía: agrega serie si cabe
    if index_in_chosen == 0 and nums:
        left = max(0, DOMICILIO_MAX - current_domicilio_len - len(name) - 1)
        serie_str = abbreviate_series_compact(nums, left)
        if serie_str and (len(name) + 1 + len(serie_str) <= DOMICILIO_MAX - current_domicilio_len):
            seg_core = f"{name} {serie_str}".strip()

    # 2ª/3ª: un número si cabe
    if index_in_chosen > 0 and nums:
        n = nums[0]
        if len(name) >= MIN_SECOND_SEG_LEN or has_two_words(name):
            if len(name) + 1 + len(n) <= DOMICILIO_MAX - current_domicilio_len:
                seg_core = f"{name} {n}".strip()

    if v["tipo"] == "PROLONGACION":
        seg = seg_core
    else:
        pref = ABREV_TIPO.get(v["tipo"])
        if DOMICILIO_WITH_PREFIX and pref and not re.match(rf'^{re.escape(pref)}\s+', seg_core, flags=re.I):
            seg = f"{pref} {seg_core}"
        else:
            seg = seg_core

    seg = re.sub(NUMTOK, '', seg, flags=re.I)
    seg = norm_spaces(seg)
    return seg

def build_domicilio_and_extra(vias, text, ext_val=None):
    """
    FIX 1: NO truncar a mitad, no aceptar tokens cortos tipo "CAMI",
    dedupe por base y por contención (PATCH F).
    + PATCH C/D: current_domicilio_len correcto + forzar 2da vía si cabe.
    """
    parts = []
    extra_segments = []
    proj_cond = extract_project_condominio_for_domicilio(text)
    if proj_cond:
        parts.append(proj_cond)

    chosen = choose_primary_vias(vias, text, top=3)
    ext_digits = only_digits(ext_val)

    def can_add(seg, current):
        seg = seg.strip()
        if not seg: return False
        if only_numbers_like(seg): return False
        if len(seg) < MIN_SECOND_SEG_LEN and not has_two_words(seg):
            return False
        already = current.split('/') if current else []
        if seg in already: return False
        return True

    def base_exists(seg, current_parts):
        b = base_via_segment(seg)
        for p in current_parts:
            if base_via_segment(p) == b:
                return True
            if is_contained_base(seg, p):  # ✅ PATCH F
                return True
        return False

    for idx, v in enumerate(chosen):
        seg = build_via_segment(
            v, text, idx,
            current_domicilio_len=len("/".join([p for p in parts if p])),  # ✅ PATCH C
            ext_digits=ext_digits if idx == 0 else None
        )
        if not seg or not seg.strip() or only_numbers_like(seg):
            continue

        if base_exists(seg, parts):
            continue

        current = "/".join(parts)
        cand = current + ("/" if current else "") + seg

        if len(cand) <= DOMICILIO_MAX and can_add(seg, current):
            parts.append(seg)
        else:
            name_only = clean_via_name(v["nombre"])
            if name_only and not base_exists(name_only, parts):
                cand2 = current + ("/" if current else "") + name_only
                if len(cand2) <= DOMICILIO_MAX and can_add(name_only, current):
                    parts.append(name_only)
                else:
                    extra_segments.append(seg)
            else:
                extra_segments.append(seg)

    domicilio = "/".join([p for p in parts if p and p.strip()])
    domicilio = truncate_by_components(domicilio, DOMICILIO_MAX)

    for seg in [s for s in extra_segments if s and s.strip() and not only_numbers_like(s)]:
        seg = norm_spaces(seg)
        if len(seg) < MIN_SECOND_SEG_LEN and not has_two_words(seg):
            continue
        current_parts = [p for p in domicilio.split("/") if p]
        if base_exists(seg, current_parts):
            continue
        cand = domicilio + ("/" if domicilio else "") + seg
        cand2 = truncate_by_components(cand, DOMICILIO_MAX)
        if cand2 == cand:
            domicilio = cand2

    # ✅ PATCH D: si hay 2 vías detectadas pero solo quedó 1 en DOMICILIO, intenta agregar la 2da vía
    chosen2 = choose_primary_vias(vias, text, top=3)
    curr_parts = [p for p in domicilio.split("/") if p]
    via_parts_count = len(curr_parts) - (1 if proj_cond and curr_parts and is_contained_base(curr_parts[0], proj_cond) else 0)

    if len(chosen2) >= 2 and via_parts_count < 2:
        seg2 = build_via_segment(
            chosen2[1], text, 1,
            current_domicilio_len=len(domicilio),
            ext_digits=None
        )
        seg2 = norm_spaces(seg2)
        if seg2 and not only_numbers_like(seg2) and len(seg2) >= MIN_SECOND_SEG_LEN:
            if not any(is_contained_base(seg2, p) for p in curr_parts):
                cand = domicilio + ("/" if domicilio else "") + seg2
                if len(cand) <= DOMICILIO_MAX:
                    domicilio = cand

    domicilio = domicilio.strip('/')
    domicilio = re.sub(r'/{2,}', '/', domicilio)
    return domicilio, extra_segments, proj_cond

def build_vias_todas(vias, text):
    names = []
    for v in vias:
        pref = ABREV_TIPO.get(v["tipo"], v["tipo"])
        name = clean_via_name(v['nombre'])
        nums, _ = numbers_near_via(text, v)
        if nums:
            serie = abbreviate_series_for_name(uniq_preserve(nums))
            name = f"{name} {serie}"
        full = f"{(pref + ' ') if pref else ''}{name}".strip()
        full = re.sub(NUMTOK, '', full, flags=re.I)
        full = norm_spaces(full)
        names.append(full)
    names = [n for n in names if n and n.strip()]
    out = " / ".join(dict.fromkeys(names))
    out = out.strip('/')
    out = re.sub(r'/{2,}', '/', out)
    return upper(out)

# -------------------------------
# INTERIOR
# -------------------------------
def _normalize_interior_val(val):
    val = upper(val or "").strip()
    mfix = re.match(r'^(\d{1,6})-[A-ZÁÉÍÓÚÜÑ]{2,}$', val, re.I)
    if mfix:
        val = mfix.group(1)
    if val in {"DE","DEL","LA","EL","LOS","LAS","Y"}:
        return ""
    if not re.search(r'\d', val) and len(val) <= 3:
        return ""
    return val

def extract_interior(text):
    numtag = r'(?:n°|nº|nro|nros|no\.?|num\.?|#)'

    patterns_numtag_first = [
        rf'\b(departamento|dep|dpto|depto)\b[^,;#\n]*?{numtag}\s*([A-Z0-9\-]+)',
        rf'\b(apartamento|apto|ap\.?|apt)\b[^,;#\n]*?{numtag}\s*([A-Z0-9\-]+)',
        rf'\b(oficina|of\.?|local|tienda|tda\.?)\b[^,;#\n]*?{numtag}\s*([A-Z0-9\-]+)',
        rf'\b(int\.?|interior)\b\.?\s*{numtag}\s*([A-Z0-9\-]+)',
        rf'\b(bloque|block|blk)\b\.?\s*{numtag}\s*([A-Z0-9\-]+)',
        rf'\b(stand|puesto|box|m[oó]dulo|modulo)\b[^,;#\n]*?{numtag}\s*([A-Z0-9\-]+)',
    ]
    for p in patterns_numtag_first:
        m = re.search(p, text, re.I)
        if m:
            val = _normalize_interior_val(m.group(2))
            return limit(val, INT_MAX) if val else ""

    patterns_fallback = [
        rf'\b(departamento|dep|dpto|depto)\b[^,;#\n]*?([A-Z0-9\-]+)',
        rf'\b(apartamento|apto|ap\.?|apt)\b[^,;#\n]*?([A-Z0-9\-]+)',
        rf'\b(oficina|of\.?|local|tienda|tda\.?)\b[^,;#\n]*?([A-Z0-9\-]+)',
        rf'\b(int\.?|interior)\b\.?\s*([A-Z0-9\-]+)',
        rf'\b(bloque|block|blk)\b\.?\s*([A-Z0-9\-]+)',
        rf'\b(stand|puesto|box|m[oó]dulo|modulo)\b[^,;#\n]*?([A-Z0-9\-]+)',
    ]
    for p in patterns_fallback:
        m = re.search(p, text, re.I)
        if m:
            val = _normalize_interior_val(m.group(2))
            return limit(val, INT_MAX) if val else ""
    return ""

# -------------------------------
# ORIENTACIÓN
# -------------------------------
def extract_orientacion(text):
    pieces = []
    for pat in [
        r'frente a[^,.;/]*',
        r'que da a[^,.;/]*',
        r'esquina(?:\s+con)?[^,.;/]*|esq\.?[^,.;/]*',
        r'cerca a[^,.;/]*',
        r'al(?:\s+)?costado de[^,.;/]*',
        r'a la altura de[^,.;/]*|altura de[^,.;/]*',
    ]:
        for m in re.finditer(pat, text, re.I):
            pieces.append(norm_spaces(m.group(0)))
    pieces = [re.sub(NUMTOK, '', p, flags=re.I) for p in pieces]
    pieces = [norm_spaces(p) for p in pieces if p and p.strip()]
    out = " / ".join(pieces)
    out = out.strip('/')
    out = re.sub(r'/{2,}', '/', out)
    return upper(out)

# -------------------------------
# REFERENCIA + RAW
# -------------------------------
ORDINALS = {
    "PRIMERO": "1", "PRIMER": "1", "PRIMERA": "1",
    "SEGUNDO": "2", "SEGUNDA": "2",
    "TERCERO": "3", "TERCERA": "3", "TERCER": "3",
    "CUARTO": "4", "CUARTA": "4",
    "QUINTO": "5", "QUINTA": "5",
    "SEXTO": "6", "SEXTA": "6",
    "SÉPTIMO": "7", "SEPTIMO": "7", "SÉPTIMA": "7", "SEPTIMA": "7",
    "OCTAVO": "8", "OCTAVA": "8",
    "NOVENO": "9", "NOVENA": "9",
    "DÉCIMO": "10", "DECIMO": "10", "DÉCIMA": "10", "DECIMA": "10",
}
ORDINALS.update({
    "DECIMO PRIMERO": "11", "DÉCIMO PRIMERO": "11",
    "DECIMO SEGUNDO": "12", "DÉCIMO SEGUNDO": "12",
    "DECIMO TERCERO": "13", "DÉCIMO TERCERO": "13",
    "DECIMO CUARTO": "14", "DÉCIMO CUARTO": "14",
    "DECIMO QUINTO": "15", "DÉCIMO QUINTO": "15",
    "DECIMO SEXTO": "16", "DÉCIMO SEXTO": "16",
    "DECIMO SEPTIMO": "17", "DÉCIMO SÉPTIMO": "17", "DECIMO SÉPTIMO": "17",
    "DECIMO OCTAVO": "18", "DÉCIMO OCTAVO": "18",
    "DECIMO NOVENO": "19", "DÉCIMO NOVENO": "19",
})

def roman_to_int(s):
    ROM = {'I':1,'V':5,'X':10,'L':50,'C':100,'D':500,'M':1000}
    s = upper(s)
    total = 0
    prev = 0
    for ch in reversed(s):
        v = ROM.get(ch,0)
        if v < prev: total -= v
        else: total += v
        prev = v
    return str(total) if total else ""

def extract_referencia(text):
    ref = []
    raw_parts = []

    piso = re.search(r'\bpiso\b\s*(?:' + NUMTOK + r'\s*)?([0-9]{1,2}|[IVXLCDM]{1,6})\b', text, re.I)
    if piso:
        val = piso.group(1)
        if re.fullmatch(r'[IVXLCDM]+', val, re.I):
            val = roman_to_int(val)
        if val:
            ref.append(f"PS{upper(val)}")
            raw_parts.append(piso.group(0))

    piso_word = re.search(
        r'\b('
        r'primer[oa]?|segund[oa]|tercer[oa]?|cuart[oa]|quint[oa]|sext[oa]|s[eé]ptim[oa]|octav[oa]|noven[oa]|'
        r'd[eé]cim[oa](?:\s+(?:primer[oa]?|segund[oa]|tercer[oa]?|cuart[oa]|quint[oa]|sext[oa]|s[eé]ptim[oa]|octav[oa]|noven[oa]))?'
        r')\b\s+(?:piso|nivel)',
        text, re.I
    )
    if piso_word:
        key = upper(strip_accents(norm_spaces(piso_word.group(1))))
        num = ORDINALS.get(key, "")
        if num:
            ref.append(f"PS{num}")
            raw_parts.append(piso_word.group(0))

    torre = re.search(r'\btorre\b[^A-Z0-9\-]*([A-Z0-9]+(?:-[A-Z0-9]+)?)', text, re.I)
    if torre:
        tok = _norm_ref_token(torre.group(1))
        if is_ref_token_valid(tok, allow_letter_only=False):
            ref.append(f"TORR.{tok}")
            raw_parts.append(torre.group(0))

    est = re.search(
        r'\b(est(?:\.|acionamiento)?|cochera)\b[^A-Z0-9\-]*?(?:' + NUMTOK + r'\s*)?([A-Z0-9]+(?:-[A-Z0-9]+)?)',
        text, re.I
    )
    if est:
        tok = _norm_ref_token(est.group(2))
        if is_ref_token_valid(tok, allow_letter_only=False):
            ref.append(f"E.{tok}")
            raw_parts.append(est.group(0))

    sot = re.search(
        r'\b(semi\s*s[oó]tano|s[oó]tano)\b[^A-Z0-9\-]*([A-Z0-9]+(?:-[A-Z0-9]+)?)',
        text, re.I
    )
    if sot:
        tok = _norm_ref_token(sot.group(2))
        if is_ref_token_valid(tok, allow_letter_only=False):
            ref.append(f"SOT.{tok}")
            raw_parts.append(sot.group(0))

    edif = re.search(r'\bedificio\b[^A-Z0-9\-]*([A-Z0-9]+(?:-[A-Z0-9]+)?)', text, re.I)
    if edif:
        tok = _norm_ref_token(edif.group(1))
        if is_ref_token_valid(tok, allow_letter_only=False):
            ref.append(f"EDIF.{tok}")
            raw_parts.append(edif.group(0))

    etp = re.search(r'\betapa\b\.?\s*([A-Z0-9IVXLCDM]+(?:-[A-Z0-9IVXLCDM]+)?)', text, re.I)
    if etp:
        raw_tok = _norm_ref_token(etp.group(1))
        tok = raw_tok
        if re.fullmatch(r'[IVXLCDM]+', raw_tok, re.I):
            tok = roman_to_int(raw_tok)
        if is_ref_token_valid(tok, allow_letter_only=False):
            ref.append(f"ETP.{tok}")
            raw_parts.append(etp.group(0))

    ui = re.search(
        r'\b(unidad(?:\s+inmobiliaria)?)\b[^A-Z0-9\-]*?(?:' + NUMTOK + r'\s*)?([A-Z0-9]+(?:-[A-Z0-9]+)?)',
        text, re.I
    )
    if ui:
        tok = _norm_ref_token(ui.group(2))
        if is_ref_token_valid(tok, allow_letter_only=False):
            tag = "U.I." if "INMOBILIARIA" in upper(ui.group(1)) else "U."
            ref.append(f"{tag}{tok}")
            raw_parts.append(ui.group(0))

    dep = re.search(r'\bdep[oó]sito\b\.?\s*(?:' + NUMTOK + r'\s*)?([A-Z0-9]+(?:-[A-Z0-9]+)?)', text, re.I)
    if dep:
        tok = _norm_ref_token(dep.group(1))
        if is_ref_token_valid(tok, allow_letter_only=False):
            ref.append(f"DEP.{tok}")
            raw_parts.append(dep.group(0))

    mz = re.search(r'\b(mz|manzana)\b\.?\s*([A-Z0-9]+(?:-[A-Z0-9]+)?)', text, re.I)
    if mz:
        tok = _norm_ref_token(mz.group(2))
        if is_ref_token_valid(tok, allow_letter_only=True):
            ref.append(f"MZ {tok}")
            raw_parts.append(mz.group(0))

    # ✅ PATCH G: LT / LOTE soporta series tipo 11-12-13-...
    lt = re.search(r'\b(lt|lote)\b\.?\s*([0-9A-Z\-\–\—\s]+)', text, re.I)
    if lt:
        span = lt.group(2)
        cut_re = re.compile(
            r'[,.;/]|' + CONNECTORS + r'|\b(distrito|provincia|departamento|urb|urbanizaci[oó]n|condominio|residencial|proyecto)\b',
            re.I
        )
        span = cut_re.split(span, 1)[0]
        nums, _ = extract_numbers_series(span)

        if not nums:
            tok = _norm_ref_token(span.strip())
            if is_ref_token_valid(tok, allow_letter_only=False):
                ref.append(f"LT {tok}")
                raw_parts.append(lt.group(0))
        else:
            for n in uniq_preserve(nums):
                ref.append(f"LT {n}")
            raw_parts.append(lt.group(0))

    ref = [re.sub(r'\([^)]*\)', '', r).strip() for r in ref]
    ref = [re.sub(NUMTOK, '', r, flags=re.I) for r in ref]
    ref = [norm_spaces(r) for r in ref if r and r.strip()]

    ref_full = "/".join(ref)
    ref_abre = truncate_by_components(ref_full, REF_MAX)
    ref_raw = upper(norm_spaces(" / ".join(raw_parts)))
    return ref_abre, ref_raw, ref_full

# -------------------------------
# UBICACIÓN
# -------------------------------
def extract_ubicacion(text):
    t = norm_spaces(text)

    def _clean_nombre(x):
        x = norm_spaces(x)
        x = re.sub(r'^[“"\'(]+|[”"\')]+$', '', x).strip()
        return x

    m = re.search(
        r'\b(urb\.?|urb|urbanizaci[oó]n)\b\.?\s*(.+?)(?='
        r'(,|;|/| - |\b(distrito|provincia|departamento)\b|$))',
        t, re.I
    )
    if m:
        return "URBANIZACION", limit(upper(_clean_nombre(m.group(2))), UBIC_MAX), upper(m.group(0))

    cut = r'(,|;|/| - |\b(distrito|provincia|departamento|edificio|piso|torre|lote|manzana|mz|lt|unidad|condominio|residencial|proyecto)\b)'

    m = re.search(r'\b(condominio|residencial)\b\s+(.+?)(?=' + cut + r'|$)', t, re.I)
    if m:
        tipo = "CONDOMINIO" if re.search('condominio', m.group(1), re.I) else "RESIDENCIAL"
        return tipo, limit(upper(_clean_nombre(m.group(2))), UBIC_MAX), upper(m.group(0))

    m = re.search(r'\bproyecto\b\s+“?(.+?)”?(?=' + cut + r'|$)', t, re.I)
    if m:
        return "PROYECTO", limit(upper(_clean_nombre(m.group(1))), UBIC_MAX), upper(m.group(0))

    return "", "", ""

# -------------------------------
# FALLBACK DOMICILIO (AGRESIVO) cuando no hay vía
# -------------------------------
def _norm_token(s: str) -> str:
    s = upper(strip_accents(norm_spaces(s)))
    s = re.sub(r'[^A-Z0-9\.\-\/ ]', '', s)
    s = norm_spaces(s)
    return s

def extract_fallback_domicilio_tokens(text):
    t = _norm_token(text)
    toks = []

    def add(x):
        x = _norm_token(x)
        if not x:
            return
        if len(x) > 28:
            x = x[:28].rstrip('.-/ ')
        if x and x not in toks:
            toks.append(x)

    for m in re.finditer(r'\bACUMULACI(?:ON|ON)\s+DE\s+PARCELA\s+([A-Z0-9\-]+)\b', t, re.I):
        add(f"ACUM.PARC.{m.group(1)}")

    for m in re.finditer(r'\bPARCELA\s+([A-Z0-9\-]+)\b', t, re.I):
        add(f"PARC.{m.group(1)}")

    m = re.search(r'\bAREA\s+REMANENTE\s+DE\s+LA\s+PARCELA\s+([A-Z0-9]+)\s+Y\s+([A-Z0-9]+)\b', t, re.I)
    if m:
        add(f"REM.PARC.{m.group(1)}-{m.group(2)}")

    for m in re.finditer(r'\bSUB\s*LOTE\s*(?:' + NUMTOK + r'\s*)?([A-Z0-9\-]+)\b', t, re.I):
        add(f"SUBLT.{m.group(1)}")

    for m in re.finditer(r'\b(?:LT|LOTE)\b\.?\s*(?:' + NUMTOK + r'\s*)?([A-Z0-9\-]+)\b', t, re.I):
        add(f"LT {m.group(1)}")

    for m in re.finditer(r'\b(?:MZ|MANZANA)\b\.?\s*([A-Z0-9\-]+)\b', t, re.I):
        add(f"MZ {m.group(1)}")

    m = re.search(r'\bFUNDO\s+([A-Z0-9 ]{3,50})', t, re.I)
    if m:
        nm = norm_spaces(m.group(1))
        nm = re.split(r'\b(,|;|/| - |\bDISTRITO\b|\bPROVINCIA\b|\bDEPARTAMENTO\b)\b', nm, maxsplit=1)[0].strip()
        if nm:
            add(f"FUNDO {nm[:22]}")

    return toks

def build_fallback_domicilio(text):
    toks = extract_fallback_domicilio_tokens(text)
    if not toks:
        return "SN"
    base = "SN"
    for tok in toks:
        cand = base + "/" + tok
        if len(cand) <= DOMICILIO_MAX:
            base = cand
        else:
            break
    return base

# -------------------------------
# ADMINISTRATIVO - PERÚ
# -------------------------------
PERU_DEPARTAMENTOS = [
    "AMAZONAS","ANCASH","APURIMAC","AREQUIPA","AYACUCHO","CAJAMARCA","CALLAO","CUSCO","HUANCAVELICA",
    "HUANUCO","ICA","JUNIN","LA LIBERTAD","LAMBAYEQUE","LIMA","LORETO","MADRE DE DIOS","MOQUEGUA",
    "PASCO","PIURA","PUNO","SAN MARTIN","TACNA","TUMBES","UCAYALI"
]
UBIGEO_DF = None

def _std(s): return upper(strip_accents(norm_spaces(s)))

def load_ubigeo(ubigeo_path):
    global UBIGEO_DF
    ext = os.path.splitext(ubigeo_path)[1].lower()
    if ext in (".xlsx", ".xls"):
        df = pd.read_excel(ubigeo_path)
    else:
        try:
            df = pd.read_csv(ubigeo_path, encoding="utf-8")
        except UnicodeDecodeError:
            df = pd.read_csv(ubigeo_path, encoding="latin-1")
    cols = { _std(c): c for c in df.columns }
    dcol = next((cols[k] for k in cols if k in ("departamento","region","dpto","depto","dep")), None)
    pcol = next((cols[k] for k in cols if k in ("provincia","prov")), None)
    tcol = next((cols[k] for k in cols if k in ("distrito","dist")), None)
    if not (dcol and pcol and tcol):
        raise ValueError("El UBIGEO debe tener columnas Departamento/Provincia/Distrito.")
    df = df.rename(columns={dcol:"DEPARTAMENTO", pcol:"PROVINCIA", tcol:"DISTRITO"})
    for c in ["DEPARTAMENTO","PROVINCIA","DISTRITO"]:
        df[c] = df[c].astype(str).map(_std)
    UBIGEO_DF = df

def _ubigeo_lookup(distrito=None, provincia=None, departamento=None):
    if UBIGEO_DF is None or not len(UBIGEO_DF): return None
    q = UBIGEO_DF
    if distrito: q = q[q["DISTRITO"] == _std(distrito)]
    if provincia and len(q): q = q[q["PROVINCIA"] == _std(provincia)]
    if departamento and len(q): q = q[q["DEPARTAMENTO"] == _std(departamento)]
    if len(q) == 1:
        r = q.iloc[0]
        return r["DISTRITO"], r["PROVINCIA"], r["DEPARTAMENTO"]
    return None

def extract_admin_peru(text):
    t = upper(strip_accents(text))
    dist = prov = dep = None

    m = re.search(r'distrito(?:\s+de)?\s+([A-ZÁÉÍÓÚÜÑ ]+)', t, re.I)
    if m:
        dist = norm_spaces(m.group(1))

    m = re.search(r'provincia(?:\s+de)?\s+([A-ZÁÉÍÓÚÜÑ ]+?)(?=\s+y\s+departamento\b|,|\.|$)', t, re.I)
    if m:
        prov = norm_spaces(m.group(1))

    m = re.search(r'provincia\s+y\s+departamento\s+de\s+([A-ZÁÉÍÓÚÜÑ ]+)', t, re.I)
    if m:
        prov = dep = norm_spaces(m.group(1))

    m = re.search(r'(departamento|region)\s+de\s+([A-ZÁÉÍÓÚÜÑ ]+)', t, re.I)
    if m:
        dep = norm_spaces(m.group(2))

    if dep is None:
        for d in PERU_DEPARTAMENTOS:
            if re.search(r'\b' + re.escape(d) + r'\b', t):
                dep = d
                break

    if UBIGEO_DF is not None and dist and (prov is None or dep is None):
        best = _ubigeo_lookup(distrito=dist, provincia=prov, departamento=dep)
        if best:
            dist, prov, dep = best

    return {
        "DISTRITO": default_sn(upper(dist) if dist else ""),
        "PROVINCIA": default_sn(upper(prov) if prov else ""),
        "DEPARTAMENTO": default_sn(upper(dep) if dep else ""),
    }

# -------------------------------
# PARSEO FINAL
# -------------------------------
def parse_direccion(d):
    d_norm = norm_spaces(d)

    vias = find_all_vias(d_norm)
    chosen = choose_primary_vias(vias, d_norm, top=3)

    admin = extract_admin_peru(d_norm)
    ext_val, ext_raw = extract_exterior(d_norm, chosen if chosen else vias)
    ref_abre0, ref_raw, ref_full = extract_referencia(d_norm)
    interior = extract_interior(d_norm)
    orient = extract_orientacion(d_norm)
    ubic_tipo, ubic, ubic_raw = extract_ubicacion(d_norm)

    domicilio, extra_segments, proj_cond_kept = build_domicilio_and_extra(vias, d_norm, ext_val=ext_val)

    # ✅ FIX 3: si NO hay vías reconocibles, aplica fallback agresivo
    if not vias and (not domicilio or domicilio == "SN"):
        domicilio = build_fallback_domicilio(d_norm)

    # ✅ PATCH A: Si NO hay vías y hay contenido útil, prefijar "SN/"
    if not vias:
        if domicilio and domicilio != "SN" and not domicilio.upper().startswith("SN/"):
            domicilio = "SN/" + domicilio

    if not domicilio:
        domicilio = "SN"

    # -------------------------------
    # ✅ PATCH G/H: coherencia LT/MZ entre REFERENCIA y DOMICILIO / N.EXTERIOR
    # -------------------------------
    dom_parts = [p.strip() for p in (domicilio or "").split("/") if p.strip()]
    dom_can = _canon_text(domicilio)
    ext_can = _canon_text(ext_val)

    # Detecta MZ en N. EXTERIOR (si existe)
    mz_ext = ""
    m_mz_ext = re.search(r'\bMZ\s+([A-Z0-9]+)\b', ext_can)
    if m_mz_ext:
        mz_ext = f"MZ {m_mz_ext.group(1)}"
        mz_ext_can = _canon_text(mz_ext)
    else:
        mz_ext_can = ""

    # --- LT: prioridad REFERENCIA, overflow a DOMICILIO, sin duplicados ---
    # 1) Trunca referencia por componentes para saber qué LTs "entran"
    ref_abre_pre = truncate_by_components(ref_full, REF_MAX)
    ref_parts_pre = [p.strip() for p in (ref_abre_pre or "").split("/") if p.strip()]

    def _lt_val(comp: str):
        m = re.match(r'^\s*LT\s+([A-Z0-9]+)\s*$', _canon_text(comp), re.I)
        return m.group(1) if m else ""

    ref_lt_kept = set()
    for p in ref_parts_pre:
        lv = _lt_val(p)
        if lv:
            ref_lt_kept.add(lv)

    # 2) Limpia DOMICILIO: si LT está en ref -> se quita del dom
    dom_parts_new = []
    for p in dom_parts:
        lv = _lt_val(p)
        if lv and lv in ref_lt_kept:
            continue
        # ✅ PATCH H: si MZ está como exterior, no repitas esa MZ en domicilio
        if mz_ext_can and _canon_text(p) == mz_ext_can:
            continue
        dom_parts_new.append(p)

    domicilio = "/".join(dom_parts_new)
    domicilio = truncate_by_components(domicilio, DOMICILIO_MAX)

    # 3) Limpia REFERENCIA: si ya está en DOMICILIO o en N.EXTERIOR, no repetir
    dom_can = _canon_text(domicilio)
    kept_ref = []
    for p in ref_parts_pre:
        pc = _canon_text(p)
        if pc and pc in dom_can:
            continue
        if pc and pc in ext_can:
            continue
        if mz_ext_can and pc == mz_ext_can:
            continue
        kept_ref.append(p)

    ref_full = "/".join(kept_ref)

    # ✅ PATCH B: Si UBICACION ya está representada en DOMICILIO, no repetirla
    if ubic_tipo and ubic and ubic_tipo in ("CONDOMINIO", "RESIDENCIAL", "URBANIZACION", "PROYECTO"):
        ub_can = _canon_text(ubic)
        if ub_can and ub_can in _canon_text(domicilio):
            ubic_tipo, ubic, ubic_raw = "", "", ""

    # Mantener tu lógica: si no hay vías -> TIPO VIA 1 por defecto AVENIDA
    tipo_via_1 = chosen[0]["tipo"] if chosen else (vias[0]["tipo"] if vias else "AVENIDA")

    # DOMICILIO siempre por componentes
    domicilio = truncate_by_components(domicilio, DOMICILIO_MAX)

    # REFERENCIA final truncada por componentes
    ref_abre = truncate_by_components(ref_full, REF_MAX)
    ref_final = ref_abre if ref_abre else "SN"

    # Limpieza final
    domicilio = re.sub(NUMTOK, '', domicilio, flags=re.I)
    domicilio = norm_spaces(domicilio).strip('/')
    domicilio = re.sub(r'/{2,}', '/', domicilio)

    ref_final = re.sub(NUMTOK, '', ref_final, flags=re.I)
    ref_final = norm_spaces(ref_final)

    return {
        "TIPO VIA 1": default_sn(tipo_via_1),
        "DOMICILIO 1": default_sn(domicilio),
        "N. EXTERIOR": default_sn(limit(ext_val, EXT_MAX)),
        "N. INTERIOR": default_sn(limit(interior, INT_MAX)),
        "REFERENCIA": default_sn(limit(ref_final, REF_MAX)),
        "UBICACION TIPO": default_sn(ubic_tipo),
        "UBICACION 1": default_sn(limit(ubic, UBIC_MAX)),
        "DISTRITO": admin["DISTRITO"],
        "PROVINCIA": admin["PROVINCIA"],
        "DEPARTAMENTO": admin["DEPARTAMENTO"],
        "VIAS (TODAS)": default_sn(build_vias_todas(vias, d_norm)),
        "ORIENTACION": default_sn(orient),
        "N. EXTERIOR RAW": default_sn(ext_raw),
        "REFERENCIA RAW": default_sn(ref_raw),
        "UBICACION RAW": default_sn(ubic_raw),
        "TEXTO NORMALIZADO": upper(d_norm),
    }
